# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Warrant < Formula
  desc ""
  homepage "https://warrant.dev"
  version "0.6.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/warrant-dev/warrant-cli/releases/download/v0.6.1/warrant-cli_Darwin_x86_64.tar.gz"
      sha256 "58ca493a36c515bed1761ede66a1cd85aa134e658b6b8a6d3a02e593b0851f7a"

      def install
        bin.install "warrant"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/warrant-dev/warrant-cli/releases/download/v0.6.1/warrant-cli_Darwin_arm64.tar.gz"
      sha256 "2d740ced6ddb407b875726f20e880a24eb7c2197b949b63d884289bf01dd9d29"

      def install
        bin.install "warrant"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/warrant-dev/warrant-cli/releases/download/v0.6.1/warrant-cli_Linux_arm64.tar.gz"
      sha256 "1def980f1034ab67abfe8645861ce056f4d56ff2af9cb1f8e9588cedb54aeeda"

      def install
        bin.install "warrant"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/warrant-dev/warrant-cli/releases/download/v0.6.1/warrant-cli_Linux_x86_64.tar.gz"
      sha256 "b77ed49ad425d56bf8bbde3ee6dbfc4e8ec23f99be4e0678662d952fb221eb1c"

      def install
        bin.install "warrant"
      end
    end
  end
end
